# Assignment 1

**Q1**

In [1]:
def fibo(N):
    if N==1:
        return 0
    elif N==2: 
        return 1
    return fibo(N-1)+fibo(N-2)
   
N=10
for i in range(1,N+1):
    print(fibo(i))

0
1
1
2
3
5
8
13
21
34


**Q2**

In [2]:
square_list=[i*i for i in range(1,21)]

cube={i:i*i*i for i in range(1,11)}
print(cube)

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}


**Q3**

In [3]:
import csv

data = [
    {"Name": "Doremon", "Age": 25, "Score": 88},
    {"Name": "Nobita", "Age": 22, "Score": 72},
    {"Name": "Sezuka", "Age": 23, "Score": 91},
    {"Name": "Gian", "Age": 24, "Score": 65},
    {"Name": "Suneo", "Age": 21, "Score": 79}
]

with open('data.csv', mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["Name", "Age", "Score"])
    writer.writeheader()
    writer.writerows(data)

with open('data.csv', mode='r') as file:
    x = csv.DictReader(file)
    for i in x:
        if int(i["Score"]) > 75:
            print(i)


{'Name': 'Doremon', 'Age': '25', 'Score': '88'}
{'Name': 'Sezuka', 'Age': '23', 'Score': '91'}
{'Name': 'Suneo', 'Age': '21', 'Score': '79'}


**Q4**

In [4]:
import numpy as np

arr = np.random.randint(10, 101, size=25)

print("Array:", arr)
x = np.max(arr)
y = np.min(arr)

maxI = np.argmax(arr)
minI = np.argmin(arr)

print("Maximum value:",x)
print("maximum value index:", maxI)

print("Minimum value:",y)
print("minimum value index:", minI)

arr[arr%2!= 0] = -1
print("Array with odd numbers replaced by -1:", arr)


Array: [13 80 49 65 11 85 47 41 49 27 69 55 42 82 69 85 91 19 15 82 66 18 41 43
 42]
Maximum value: 91
maximum value index: 16
Minimum value: 11
minimum value index: 4
Array with odd numbers replaced by -1: [-1 80 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 42 82 -1 -1 -1 -1 -1 82 66 18 -1 -1
 42]


**Q5**

In [5]:
import numpy as np

mat = np.random.randint(1, 100, size=(5, 5))
diagonal = np.diag(mat)
print("Matrix:\n", mat)

print("Diagonal Elements:", diagonal)

sum= np.sum(np.triu(mat, k=1))
print("Sum of elements above the main diagonal:", sum)


Matrix:
 [[85 13  5 90 63]
 [14 27 73 28 73]
 [84 33 88 28 44]
 [50 78 23 58 54]
 [36 52 80 72  7]]
Diagonal Elements: [85 27 88 58  7]
Sum of elements above the main diagonal: 471


**Q6**

In [6]:
import numpy as np

arr = np.random.random((3, 4, 5))

print("Array:\n", arr)
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
normal_arr = (arr - mean) / std_dev

print("Normal Array:\n", normal_arr)


Array:
 [[[0.56248726 0.34381461 0.08283418 0.99871633 0.07443255]
  [0.737383   0.28893792 0.56933076 0.61207691 0.60946258]
  [0.88464221 0.33358687 0.85121468 0.93328514 0.05272139]
  [0.42014292 0.61724603 0.91562099 0.50846192 0.47691269]]

 [[0.27479609 0.96163857 0.84924178 0.00891757 0.6639764 ]
  [0.66049608 0.4752016  0.41284539 0.44344716 0.04224106]
  [0.56935542 0.29772277 0.54615045 0.23030574 0.92588362]
  [0.93011843 0.48625022 0.21479892 0.89399748 0.31266784]]

 [[0.93404783 0.54657414 0.87840291 0.58859793 0.82057097]
  [0.88718443 0.65943701 0.13072683 0.55206429 0.07936952]
  [0.45999718 0.58374139 0.61694157 0.54789121 0.9116209 ]
  [0.84400393 0.66716337 0.88897969 0.24908383 0.41522451]]]
Mean: 0.5555831158273222
Median: 0.5659090102378987
Standard Deviation: 0.2773122697781943
Normal Array:
 [[[ 0.02489665 -0.76364635 -1.70475304  1.59795746 -1.73504969]
  [ 0.65557824 -0.96153409  0.04957459  0.20371907  0.19429166]
  [ 1.18660128 -0.80052802  1.06606016  1.36

**Q7**

In [7]:
import numpy as np

arr1 = np.random.randint(1, 15, size=(4, 4))

arr2 = np.random.randint(1, 15, size=(4, 1))
res = arr1 + arr2
print("Array1 (4x4):\n", arr1)
print("Array2 (4x1):\n", arr2)


print("Result of Broadcasting Addition:\n", res)


Array1 (4x4):
 [[10  5 14  1]
 [ 2 14 11  1]
 [ 2 13  6  7]
 [ 5 12  9  8]]
Array2 (4x1):
 [[11]
 [ 4]
 [ 1]
 [ 1]]
Result of Broadcasting Addition:
 [[21 16 25 12]
 [ 6 18 15  5]
 [ 3 14  7  8]
 [ 6 13 10  9]]
